Import("env")

env.Program("empty.c")
env.Program("simple.c")
env.Program("sleep.c")
env.Program("queue.c")
env.Program("list.c")
env.Program("sem.c")
env.Program("mutex.c")

env.Program("water_sem.c")
env.Program("water_cond.c")
