Import("env")

librt = env.StaticLibrary(
    target="rt",
    source=[
        "rt.c",
        "tick.c",
        "critical.c",
        "sleep.c",
        "queue.c",
        "list.c",
        "sem.c",
    ],
)

Return("librt")
