Import("env")

librt = env.StaticLibrary(
    target="rt",
    source=[
        "cond.c",
        "list.c",
        "mutex.c",
        "queue.c",
        "rt.c",
        "sem.c",
    ],
)

Return("librt")
